### ISSUE TITLE
Vue dependency missing?

### ISSUE THREAD

**Issue by bachi76** [GIVESocialMovement/sbt-vuefy#11]
I've run into an error when starting the app:

> ERROR in ./vue/components/common/our-button.vue
Module build failed: Error: 
> Vue packages version mismatch:
> - vue@2.1.10
> - vue-template-compiler@2.5.16

It was using my old version and `npm install vue` helped, but I suggest to add vue itself also as dependency to ensure this works out of the box.

Cool project - exactly what we consider using in our next project. Thanks!

**Comment by bachi76** [comment]
Yes, I've initially used `yarn install` as mentioned in the readme, then the problem appeared.

**Comment by tanin47** [comment]
Could you share when the problem occurred? Was it during `yarn install` or during compilation?

**Comment by bachi76** [comment]
During compilation, triggerred by the first page load. The yarn install went smooth (didn't check all output though).

**Comment by tanin47** [comment]
That's a good insight. I was hoping that the project was self-contained and that `webpack` didn't use any external library (e.g. global vue). `webpack` should have used only the libraries in `./node_modules`. 

I'll find a way to fix this.

**Comment by tanin47** [comment]
I think I understand the exception now. The error actually means `vue@2.1.10` and `vue-template-compiler@2.5.16` can't co-exist. (See additional error message here: https://github.com/vuejs/vue-loader/issues/470)

My machine doesn't have `vue` installed (e.g. `npm -g list` and `yarn global list` don't contain `vue`).

Since `vue-template-compiler` doesn't need `vue`, I'm not sure why `yarn` check for version mismatch. It might be possible that they have common dependencies. Those common dependencies' version should match.

I'm going to close this as wontfix. I wouldn't like to include an unnecesary dependency, though it is nice to have.
